### ISSUE TITLE
How can i get paymentId when i am using razorpay

### ISSUE THREAD

**Issue by raginisahu** [sagarnayak/paymentGatewayServer#1]

**Comment by sagarnayak** [comment]
payment id is received from the client end. if you are using it on the web or android. there you can get the payment id. [andriod implementation for you ref](https://github.com/sagarnayak/PaymentGateway/blob/2d0e91ac2d2c09d39746f1fb7739575e77a99e25/app/src/main/java/com/sagar/android/paymentgateway/ui/item_list/ItemsList.kt#L188)

**Comment by raginisahu** [comment]
Thanks
